const swamp_smells = [
  { value: 'mossy decay', probability: 1 },
  { value: 'stagnant water', probability: 1 },
  { value: 'muddy earth', probability: 1 },
  { value: 'rotting vegetation', probability: 1 },
  { value: 'sulfurous gas', probability: 1 },
  { value: 'wildflowers', probability: 0.7 },
  { value: 'peat smoke', probability: 0.6 },
  { value: 'wet stone', probability: 0.9 },
  { value: 'algae bloom', probability: 0.8 },
  { value: 'fermented fruit', probability: 0.5 },
  { value: 'fishy odor', probability: 0.9 },
  { value: 'a potent musk', probability: 0.6 },
  { value: 'damp wood', probability: 1 },
  { value: 'pungent mildew', probability: 1 },
  { value: 'cypress sap', probability: 0.8 },
  { value: 'insect nectar', probability: 0.5 },
  { value: 'brackish water', probability: 1 },
  { value: 'charred reeds', probability: 0.4 },
  { value: 'marshland blooms', probability: 0.7 },
  { value: 'moldy undergrowth', probability: 1 },
]

const grassland_smells = [
  { value: 'fresh grass', probability: 1 },
  { value: 'wildflowers', probability: 0.8 },
  { value: 'sun-warmed earth', probability: 1 },
  { value: 'crushed herbs', probability: 0.7 },
  { value: 'dried hay', probability: 0.9 },
  { value: 'sweet clover', probability: 0.6 },
  { value: 'dew-soaked vegetation', probability: 1 },
  { value: 'animal musk', probability: 0.5 },
  { value: 'honeyed blossoms', probability: 0.7 },
  { value: 'smoky campfire', probability: 0.4 },
  { value: 'wind-carried pollen', probability: 0.8 },
  { value: 'ripened grain', probability: 0.6 },
  { value: 'sun-dried manure', probability: 0.3 },
  { value: 'minty wild thyme', probability: 0.5 },
  { value: 'aromatic sage', probability: 0.4 },
  { value: 'cool morning air', probability: 1 },
  { value: 'rain-damp soil', probability: 0.9 },
  { value: 'smoky prairie fires', probability: 0.3 },
  { value: 'earthy root scents', probability: 0.6 },
  { value: 'wind-swept dust', probability: 0.7 },
]

const forest_smells = [
  { value: 'pine needles', probability: 1 },
  { value: 'damp earth', probability: 1 },
  { value: 'decaying leaves', probability: 0.9 },
  { value: 'fresh moss', probability: 0.8 },
  { value: 'wildflowers', probability: 0.7 },
  { value: 'wood smoke', probability: 0.6 },
  { value: 'ferns after rain', probability: 0.9 },
  { value: 'bark sap', probability: 0.8 },
  { value: 'crushed berries', probability: 0.7 },
  { value: 'mushrooms', probability: 0.8 },
  { value: 'cedar wood', probability: 0.9 },
  { value: 'rotting wood', probability: 0.6 },
  { value: 'spring blossoms', probability: 0.7 },
  { value: 'charcoal from an old fire', probability: 0.5 },
  { value: 'animal musk', probability: 0.6 },
  { value: 'fresh rain on leaves', probability: 1 },
  { value: 'wild mint', probability: 0.4 },
  { value: 'fallen acorns', probability: 0.7 },
  { value: 'cool mist', probability: 0.8 },
  { value: 'oak sap', probability: 0.6 },
  { value: 'smoke from a distant campfire', probability: 0.5 },
  { value: 'honeysuckle', probability: 0.7 },
  { value: 'wet bark', probability: 0.9 },
  { value: 'forest flowers', probability: 0.6 },
  { value: 'rich humus', probability: 1 },
]

const rotting_smells = [
  { value: 'putrid', probability: 1 },
  { value: 'sour', probability: 1 },
  { value: 'musty', probability: 1 },
  { value: 'rancid', probability: 1 },
  { value: 'earthy', probability: 1 },
  { value: 'fermented', probability: 1 },
  { value: 'moldy', probability: 1 },
  { value: 'metallic', probability: 1 },
  { value: 'pungent', probability: 1 },
  { value: 'cloying', probability: 1 },
  { value: 'fishy', probability: 1 },
  { value: 'acrid', probability: 1 },
  { value: 'stale', probability: 1 },
  { value: 'fetid', probability: 1 },
  { value: 'smoky', probability: 1 },
  { value: 'chemical', probability: 1 },
  { value: 'sulfuric', probability: 1 },
  { value: 'gamey', probability: 1 },
  { value: 'vinegary', probability: 1 },
]

const underdark_smells = [
  { value: 'damp stone', probability: 1 },
  { value: 'moldy earth', probability: 1 },
  { value: 'sulfur', probability: 0.9 },
  { value: 'stagnant water', probability: 0.8 },
  { value: 'rotting vegetation', probability: 0.7 },
  { value: 'metallic tang', probability: 0.6 },
  { value: 'lichen', probability: 0.8 },
  { value: 'guano', probability: 0.9 },
  { value: 'fungal spores', probability: 1 },
  { value: 'smoke from deep fissures', probability: 0.7 },
  { value: 'ozone', probability: 0.6 },
  { value: 'charred rock', probability: 0.5 },
  { value: 'earthy minerals', probability: 0.8 },
  { value: 'burnt sulfur', probability: 0.7 },
  { value: 'acrid fumes', probability: 0.6 },
  { value: 'freshly unearthed soil', probability: 0.9 },
  { value: 'decaying organic matter', probability: 0.8 },
  { value: 'algae bloom', probability: 0.7 },
  { value: 'subterranean river', probability: 0.6 },
  { value: 'iron ore', probability: 0.7 },
  { value: 'petroleum seep', probability: 0.5 },
  { value: 'phosphorescent fungus', probability: 0.8 },
  { value: 'bone dust', probability: 0.7 },
  { value: 'stale air', probability: 1 },
  { value: 'brimstone', probability: 0.6 },
]

const hill_smells = [
  { value: 'Freshly cut grass', probability: 1 },
  { value: 'Wildflowers blooming among the hills', probability: 0.9 },
  { value: 'Damp earth after a light rain', probability: 1 },
  { value: 'The faint scent of pine from a distant grove', probability: 0.8 },
  { value: 'The warm, dry smell of sunbaked rocks', probability: 0.7 },
  { value: 'The earthy scent of grazing animals', probability: 0.6 },
  { value: 'The tangy aroma of wild herbs growing nearby', probability: 0.9 },
  { value: 'The faint musk of nearby sheep', probability: 0.7 },
  {
    value: 'The sweet smell of clover scattered across the hill',
    probability: 0.8,
  },
  { value: 'The clean, crisp scent of mountain air', probability: 0.9 },
  { value: 'The subtle fragrance of flowering shrubs', probability: 0.6 },
  { value: 'The rich smell of freshly turned soil', probability: 0.7 },
  { value: 'The sharp scent of crushed thyme underfoot', probability: 0.8 },
  { value: 'The faint whiff of smoke from a distant fire', probability: 0.6 },
  { value: 'The subtle musk of damp moss on rocks', probability: 0.7 },
  {
    value: 'The spicy aroma of wild sage growing in patches',
    probability: 0.8,
  },
  { value: 'The tang of cool morning dew on the grass', probability: 0.9 },
  {
    value: 'The faint, floral perfume of lavender in bloom',
    probability: 0.7,
  },
  { value: 'The heavy scent of rain-soaked grass', probability: 0.8 },
  { value: 'The mineral tang of a nearby spring', probability: 0.6 },
  { value: 'The faint smell of hay carried on the wind', probability: 0.7 },
  { value: 'The resinous scent of juniper trees', probability: 0.6 },
  {
    value: 'The faint odor of cattle grazing in the distance',
    probability: 0.7,
  },
  { value: 'The slightly metallic scent of wet rocks', probability: 0.8 },
  { value: 'The refreshing smell of wind-whipped grass', probability: 0.9 },
]

const coastal_smells = [
  { value: 'The salty tang of sea air', probability: 1 },
  { value: 'The faintly metallic scent of wet rocks', probability: 0.9 },
  { value: 'The briny aroma of seaweed washed ashore', probability: 0.8 },
  { value: 'The rich, damp smell of sand', probability: 1 },
  {
    value: 'The subtle sweetness of marine flowers in bloom',
    probability: 0.7,
  },
  { value: 'The faint scent of sun-warmed driftwood', probability: 0.8 },
  {
    value: 'The sharp, clean smell of ozone before a storm',
    probability: 0.7,
  },
  { value: 'The fishy odor of a tide pool', probability: 0.9 },
  { value: 'The pungent smell of decaying seaweed', probability: 0.6 },
  {
    value: 'The faint whiff of salt-crusted wood from a dock',
    probability: 0.8,
  },
  { value: 'The earthy smell of wet sand at low tide', probability: 0.9 },
  { value: 'The rich, smoky scent of a nearby bonfire', probability: 0.6 },
  { value: 'The faint aroma of fresh-caught fish', probability: 0.7 },
  { value: 'The tang of algae blooming in a tide pool', probability: 0.8 },
  { value: 'The warm, slightly burnt smell of tarred rope', probability: 0.6 },
  {
    value: 'The light perfume of distant wildflowers on cliffs',
    probability: 0.7,
  },
  { value: 'The sharp smell of drying shells on the beach', probability: 0.8 },
  {
    value: 'The faint odor of sea spray carried by the wind',
    probability: 0.9,
  },
  { value: 'The warm, earthy scent of sunbaked rocks', probability: 0.8 },
  { value: 'The pungent musk of rotting driftwood', probability: 0.6 },
  {
    value: 'The subtle aroma of distant rain over the water',
    probability: 0.7,
  },
  { value: 'The spicy, herbal smell of sea grasses', probability: 0.8 },
  { value: 'The clean scent of freshly turned sand', probability: 0.9 },
  {
    value: 'The faint hint of citrus from distant lemon groves',
    probability: 0.5,
  },
  { value: 'The slightly metallic tang of sea salt', probability: 1 },
]

const sweet_smells = [
  { value: 'vanilla', probability: 1 },
  { value: 'lavender', probability: 1 },
  { value: 'citrus', probability: 1 },
  { value: 'jasmine', probability: 1 },
  { value: 'rose', probability: 1 },
  { value: 'mint', probability: 1 },
  { value: 'honeysuckle', probability: 1 },
  { value: 'fresh linen', probability: 1 },
  { value: 'eucalyptus', probability: 1 },
  { value: 'pine', probability: 1 },
  { value: 'almond', probability: 1 },
  { value: 'orchid', probability: 1 },
  { value: 'coconut', probability: 1 },
  { value: 'apple blossom', probability: 1 },
  { value: 'lemon balm', probability: 1 },
  { value: 'lilac', probability: 1 },
  { value: 'fresh rainwater', probability: 1 },
  { value: 'gardenia', probability: 1 },
  { value: 'chamomile', probability: 1 },
  { value: 'white tea', probability: 1 },
]

const stone_smells = [
  { value: 'damp', probability: 1 },
  { value: 'earthy', probability: 1 },
  { value: 'mineral', probability: 1 },
  { value: 'metallic', probability: 1 },
  { value: 'musty', probability: 1 },
]

export default {
  // Regional Smells
  grassland_smells,
  swamp_smells,
  forest_smells,
  hill_smells,
  coastal_smells,
  underdark_smells,

  // Ambient Smells
  rotting_smells,
  sweet_smells,
  stone_smells,
}
