const swamp_smells = [
  { value: 'mossy decay', probability: 1 },
  { value: 'stagnant water', probability: 1 },
  { value: 'muddy earth', probability: 1 },
  { value: 'rotting vegetation', probability: 1 },
  { value: 'sulfurous gas', probability: 1 },
  { value: 'wildflowers', probability: 0.7 },
  { value: 'peat smoke', probability: 0.6 },
  { value: 'wet stone', probability: 0.9 },
  { value: 'algae bloom', probability: 0.8 },
  { value: 'fermented fruit', probability: 0.5 },
  { value: 'fishy odor', probability: 0.9 },
  { value: 'a potent musk', probability: 0.6 },
  { value: 'damp wood', probability: 1 },
  { value: 'pungent mildew', probability: 1 },
  { value: 'cypress sap', probability: 0.8 },
  { value: 'insect nectar', probability: 0.5 },
  { value: 'brackish water', probability: 1 },
  { value: 'charred reeds', probability: 0.4 },
  { value: 'marshland blooms', probability: 0.7 },
  { value: 'moldy undergrowth', probability: 1 },
]

const grassland_smells = [
  { value: 'fresh grass', probability: 1 },
  { value: 'wildflowers', probability: 0.8 },
  { value: 'sun-warmed earth', probability: 1 },
  { value: 'crushed herbs', probability: 0.7 },
  { value: 'dried hay', probability: 0.9 },
  { value: 'sweet clover', probability: 0.6 },
  { value: 'dew-soaked vegetation', probability: 1 },
  { value: 'animal musk', probability: 0.5 },
  { value: 'honeyed blossoms', probability: 0.7 },
  { value: 'smoky campfire', probability: 0.4 },
  { value: 'wind-carried pollen', probability: 0.8 },
  { value: 'ripened grain', probability: 0.6 },
  { value: 'sun-dried manure', probability: 0.3 },
  { value: 'minty wild thyme', probability: 0.5 },
  { value: 'aromatic sage', probability: 0.4 },
  { value: 'cool morning air', probability: 1 },
  { value: 'rain-damp soil', probability: 0.9 },
  { value: 'smoky prairie fires', probability: 0.3 },
  { value: 'earthy root scents', probability: 0.6 },
  { value: 'wind-swept dust', probability: 0.7 },
]

const forest_smells = [
  { value: 'pine needles', probability: 1 },
  { value: 'damp earth', probability: 1 },
  { value: 'decaying leaves', probability: 0.9 },
  { value: 'fresh moss', probability: 0.8 },
  { value: 'wildflowers', probability: 0.7 },
  { value: 'wood smoke', probability: 0.6 },
  { value: 'ferns after rain', probability: 0.9 },
  { value: 'bark sap', probability: 0.8 },
  { value: 'crushed berries', probability: 0.7 },
  { value: 'mushrooms', probability: 0.8 },
  { value: 'cedar wood', probability: 0.9 },
  { value: 'rotting wood', probability: 0.6 },
  { value: 'spring blossoms', probability: 0.7 },
  { value: 'charcoal from an old fire', probability: 0.5 },
  { value: 'animal musk', probability: 0.6 },
  { value: 'fresh rain on leaves', probability: 1 },
  { value: 'wild mint', probability: 0.4 },
  { value: 'fallen acorns', probability: 0.7 },
  { value: 'cool mist', probability: 0.8 },
  { value: 'oak sap', probability: 0.6 },
  { value: 'smoke from a distant campfire', probability: 0.5 },
  { value: 'honeysuckle', probability: 0.7 },
  { value: 'wet bark', probability: 0.9 },
  { value: 'forest flowers', probability: 0.6 },
  { value: 'rich humus', probability: 1 },
]

const rotting_smells = [
  { value: 'putrid', probability: 1 },
  { value: 'sour', probability: 1 },
  { value: 'musty', probability: 1 },
  { value: 'rancid', probability: 1 },
  { value: 'earthy', probability: 1 },
  { value: 'fermented', probability: 1 },
  { value: 'moldy', probability: 1 },
  { value: 'metallic', probability: 1 },
  { value: 'pungent', probability: 1 },
  { value: 'cloying', probability: 1 },
  { value: 'fishy', probability: 1 },
  { value: 'acrid', probability: 1 },
  { value: 'stale', probability: 1 },
  { value: 'fetid', probability: 1 },
  { value: 'smoky', probability: 1 },
  { value: 'chemical', probability: 1 },
  { value: 'sulfuric', probability: 1 },
  { value: 'gamey', probability: 1 },
  { value: 'vinegary', probability: 1 },
]

const underdark_smells = [
  { value: 'damp stone', probability: 1 },
  { value: 'moldy earth', probability: 1 },
  { value: 'sulfur', probability: 0.9 },
  { value: 'stagnant water', probability: 0.8 },
  { value: 'rotting vegetation', probability: 0.7 },
  { value: 'metallic tang', probability: 0.6 },
  { value: 'lichen', probability: 0.8 },
  { value: 'guano', probability: 0.9 },
  { value: 'fungal spores', probability: 1 },
  { value: 'smoke from deep fissures', probability: 0.7 },
  { value: 'ozone', probability: 0.6 },
  { value: 'charred rock', probability: 0.5 },
  { value: 'earthy minerals', probability: 0.8 },
  { value: 'burnt sulfur', probability: 0.7 },
  { value: 'acrid fumes', probability: 0.6 },
  { value: 'freshly unearthed soil', probability: 0.9 },
  { value: 'decaying organic matter', probability: 0.8 },
  { value: 'algae bloom', probability: 0.7 },
  { value: 'subterranean river', probability: 0.6 },
  { value: 'iron ore', probability: 0.7 },
  { value: 'petroleum seep', probability: 0.5 },
  { value: 'phosphorescent fungus', probability: 0.8 },
  { value: 'bone dust', probability: 0.7 },
  { value: 'stale air', probability: 1 },
  { value: 'brimstone', probability: 0.6 },
]

export default {
  grassland_smells,
  swamp_smells,
  forest_smells,
  underdark_smells,
  rotting_smells,
}
