const swamp_smells = [
  { value: 'mossy decay', probability: 1 },
  { value: 'stagnant water', probability: 1 },
  { value: 'muddy earth', probability: 1 },
  { value: 'rotting vegetation', probability: 1 },
  { value: 'sulfurous gas', probability: 1 },
  { value: 'wildflowers', probability: 0.7 },
  { value: 'peat smoke', probability: 0.6 },
  { value: 'wet stone', probability: 0.9 },
  { value: 'algae bloom', probability: 0.8 },
  { value: 'fermented fruit', probability: 0.5 },
  { value: 'fishy odor', probability: 0.9 },
  { value: 'a potent musk', probability: 0.6 },
  { value: 'damp wood', probability: 1 },
  { value: 'pungent mildew', probability: 1 },
  { value: 'cypress sap', probability: 0.8 },
  { value: 'insect nectar', probability: 0.5 },
  { value: 'brackish water', probability: 1 },
  { value: 'charred reeds', probability: 0.4 },
  { value: 'marshland blooms', probability: 0.7 },
  { value: 'moldy undergrowth', probability: 1 },
]

const grassland_smells = [
  { value: 'fresh grass', probability: 1 },
  { value: 'wildflowers', probability: 0.8 },
  { value: 'sun-warmed earth', probability: 1 },
  { value: 'crushed herbs', probability: 0.7 },
  { value: 'dried hay', probability: 0.9 },
  { value: 'sweet clover', probability: 0.6 },
  { value: 'dew-soaked vegetation', probability: 1 },
  { value: 'animal musk', probability: 0.5 },
  { value: 'honeyed blossoms', probability: 0.7 },
  { value: 'smoky campfire', probability: 0.4 },
  { value: 'wind-carried pollen', probability: 0.8 },
  { value: 'ripened grain', probability: 0.6 },
  { value: 'sun-dried manure', probability: 0.3 },
  { value: 'minty wild thyme', probability: 0.5 },
  { value: 'aromatic sage', probability: 0.4 },
  { value: 'cool morning air', probability: 1 },
  { value: 'rain-damp soil', probability: 0.9 },
  { value: 'smoky prairie fires', probability: 0.3 },
  { value: 'earthy root scents', probability: 0.6 },
  { value: 'wind-swept dust', probability: 0.7 },
]

export default { grassland_smells, swamp_smells }
