const swamp_sounds = [
  { value: 'croaking frogs', probability: 1 },
  { value: 'buzzing insects', probability: 1 },
  { value: 'splashing water', probability: 0.9 },
  { value: 'chirping crickets', probability: 1 },
  { value: 'rustling reeds', probability: 0.8 },
  { value: 'bird calls', probability: 0.7 },
  { value: 'distant thunder', probability: 0.4 },
  { value: 'gurgling streams', probability: 0.9 },
  { value: 'howling wind', probability: 0.6 },
  { value: 'plopping sounds', probability: 0.8 },
  { value: 'splashing fish', probability: 0.7 },
  { value: 'snapping branches', probability: 0.5 },
  { value: 'low growls', probability: 0.3 },
  { value: 'wing beats', probability: 0.6 },
  { value: 'distant murmurs', probability: 0.4 },
  { value: 'hissing snakes', probability: 0.3 },
  { value: 'dripping water', probability: 1 },
  { value: 'slurping mud', probability: 0.7 },
  { value: 'groaning trees', probability: 0.5 },
  { value: 'chittering rodents', probability: 0.6 },
]

const grassland_sounds = [
  { value: 'rustling grass', probability: 1 },
  { value: 'chirping crickets', probability: 1 },
  { value: 'singing birds', probability: 0.9 },
  { value: 'buzzing bees', probability: 0.8 },
  { value: 'whistling wind', probability: 1 },
  { value: 'lowing cattle', probability: 0.6 },
  { value: 'fluttering wings', probability: 0.7 },
  { value: 'distant thunder', probability: 0.4 },
  { value: 'howling coyotes', probability: 0.3 },
  { value: 'bubbling streams', probability: 0.8 },
  { value: 'galloping hooves', probability: 0.5 },
  { value: 'crunching footsteps', probability: 0.6 },
  { value: 'grassy sways', probability: 0.7 },
  { value: 'insect droning', probability: 1 },
  { value: 'distant whoops', probability: 0.4 },
  { value: 'leaping antelope', probability: 0.5 },
  { value: 'rustling bushes', probability: 0.7 },
  { value: 'morning bird calls', probability: 0.9 },
  { value: 'evening frog croaks', probability: 0.6 },
  { value: 'rolling thunderclaps', probability: 0.3 },
]

export default { grassland_sounds, swamp_sounds }
