version: '3.9'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
      - '9229:9229' # Debugger port
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: npm run dev

  db:
    container_name: postgres
    image: postgres
    ports:
      - '${DB_EXTERNAL_PORT}:${DB_PORT}'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  data: {}
